version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - cp -r build/* .
artifacts:
  files:
    - '**/*'
  base-directory: build